### ISSUE TITLE
209A: Were you ever a ‘couple’? may be missing a none-of-the-above

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#177]
The first set of questions (dating/engaged) doesn't have an option for none of the above. Can the abuser be a person who was never dating or engaged to the defendant?

Not sure if it's a bug or not, but it currently looks like a possibly breaking one to me. Feel free to change the label.

**Comment by plocket** [comment]
Interestingly enough, it was marked as required (with a red `*`), but I was able to continue without marking an answer. Is that intentional?

**Comment by nonprofittechy** [comment]
I think this is an intentional design choice.

![image](https://user-images.githubusercontent.com/7645641/81723058-47bbb580-9450-11ea-91d3-a1172b251a54.png)

This is meant to read as one set of checkboxes where you can check any boxes that apply.

I think the design was to avoid showing a "none of the above" in the middle of the screen. @CaroRob -- thoughts? It reads naturally this way with the "subquestion" text. 

required `checkboxes` doesn't do anything unless you have a `none of the above` or a `minlength`. I think best solution is to turn off the `required` on the top so you don't see a red *

The only question on this screen it makes sense would always have an option checked is the marriage one--only 3 options there.

**Comment by nonprofittechy** [comment]
I turned off the required modifier on the top checkbox--will include in next commit. We can revisit this with user testing, but I think it makes sense this way.
