### ISSUE TITLE
209A: Green vocabulary terms 

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#244]
SMEs reported not noticing what the green highlighted terms were.  Also Chris pointed out that the green may be an issue for people with red/green colorblindness.

@CaroRob Is there an another way to deal with this?

**Comment by CaroRob** [comment]
red/green color blindness means people cannot see the difference between red and green - not that they cannot see the distinction between these colors and black or grey on contrasting background. However I did raise this issue with Jonathan a few years ago - didn't get much response because partly I am not sure I have an alternate solution. Michelle suggests putting little question mark icons in but I think these icons in the middle of text is far more disruptive to people struggling to read. Parentheses are a known barrier, I believe icons are even more distracting and interrupt any flow. I think this is a good argument for a how to use this interview path... either force or optional in which we explain about green text It is a weird feature, but once you know what it is and can recognize it a smooth way to introduce more information that does not contribute to overload. My best solution would be to explain what and how green text works, then try it out.

**Comment by nonprofittechy** [comment]
We define these now. May want a better solution later, but I think this is good.
