### ISSUE TITLE
209A - Auto-capitalization of Name(s) entered

### ISSUE THREAD

**Issue by jodicantrell** [SuffolkLITLab/docassemble-MAVirtualCourt#332]
My first & last name was capitalized automatically, but not my middle name.  And there was no auto-capitalization when I input the first/middle/last name of the person I’m getting the restraining order against (“my”) – all 3 stayed lower case - - and so the name showed up lower case on all the subsequent screens – AND in the forms…..my name showed up capitalized (“Jodi”)

[209A - Test.pdf](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/files/4718264/209A.-.Test.pdf)

**Comment by nonprofittechy** [comment]
I think this is a very browser-specific behavior. Some input fields cause the browser to capitalize. It is not a behavior we selected. We may be able to investigate turning off this behavior using browser-specific configuration options, but I think beyond scope of our project.

We also cannot apply capitalization to people's names that they do not explicitly choose; we need to respect the way they enter it. Since this is something people can control in their browser and they see the capitalization before clicking next, I think this is working as designed.

https://www.kalzumeus.com/2010/06/17/falsehoods-programmers-believe-about-names/
