### ISSUE TITLE
Email to court function: No email entry for "Boston Juvenile Court" in court_emails.yml

### ISSUE THREAD

**Issue by nonprofittechy** [SuffolkLITLab/docassemble-MAVirtualCourt#421]
![image](https://user-images.githubusercontent.com/7645641/85480012-40c6ad80-b58d-11ea-9552-a305aabdfc45.png)

**Comment by BryceStevenWilley** [comment]
Looks like this is because it should be "Suffolk Juvenile Court", which is in courts.yml? https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/blob/7124077fa400e67febea83ed524f5c6764d3a7b5/docassemble/MAVirtualCourt/data/sources/court_emails.yml#L116

This issues is a bit old, but do you remember what interview this was on?

**Comment by BryceStevenWilley** [comment]
Don't think this is relevant anymore, "Boston Juvenile Court" doesn't show up anywhere outside of this issue and one different case in the SCDAO form.
