### ISSUE TITLE
209A: Defendant Information Form - Get rid of addenda

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#477]
Test case 2.11 - Defendant Information Form Triggered Addenda.  Per previous discussions, I think we want may want to rely on character limits rather than addenda for the Defendant Information Form, because this form is transmitted to the police for purposes of locating the defendant, and I don't really trust the court to transmit an addenda to the police and/or trust the police to look at an addenda.  I'd rather force everything onto the one page if at all possible.

**Comment by CaroRob** [comment]
I've added character limits to all fields that do not already have an addendum - PR 502 https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/502 [commit d54f8b64125f5b65f4ef16f07e5931af72aa088b](https://github.com/SuffolkLITLab/docassemble-MAVirtualCourt/pull/502/commits/d54f8b64125f5b65f4ef16f07e5931af72aa088b)

**Comment by CaroRob** [comment]
Got a branch for this -  567_defendant_info_addenda  - because issue #567 
We had a couple of fields that were missing maxlength but also some of the fields on the PDF are combinations of multiple fields in interview so we had to figure out a way to limit the final field.
These fields are physical characteristics other_parties[0].physical_other_details and where to find defendant. other_parties[0].location_information_other 

Pending Kate's approval of the latter solution, limiting best places to find defendant to 300 characters, best times to 125 and other places police might find defendant's to 300 whatever users don't use in these 3 fields together plus another 50 characters becomes the limit for the final box in which users can add anything more. This keeps all info limited to the Defendant Information Sheet.
