### ISSUE TITLE
209A: Text date fields

### ISSUE THREAD

**Issue by plocket** [SuffolkLITLab/docassemble-MAVirtualCourt#495]
# Survey result on row 111

**Report type:** I'd like to tell you something else.

**Contact info**: Page id: other cases, v0.96

---

### Bug

Question | Answer
---|---
**Question** | 
**Actions** | 
**Expected** | 
**Actual** | 
**Feedback** | 

---

### Confusion feedback

Question | Answer
---|---
**Question** | 
**Confusion** | 
**Feedback** | 

---

### Something else

Uncategorized Feedback:
Decision to make dates fields text and not specific dates? Just asking.

---

### Test report

Question | Answer
---|---
**Link to spreadsheet** | 
**Test id** | 
**Tester** | 
**Question** | 
**Input** | 
**Expected** | 
**Actual** | 
**Link** | 
**Pic** | 
**Notes** | 

**Error message**
```

```

---

### Thank you!

**Comment by kateleebarry** [comment]
Not sure who made this issue or where in the interview it's referring to, but if this is referring to the affidavit, that was a deliberate decision to allow people to write in non-exact dates like "last summer," etc.

**Comment by nonprofittechy** [comment]
Similar reasoning. The issue included the page ID--this is the page where we ask people to tell us about other cases with the Defendant other than past care/custody proceedings. 

It's not likely for people to know or important for them to say the exact date of a past case they had with the Defendant. Not sure it would be easy for them to answer even with the docket, because is it the starting date? Date of last court action? date of final decision? Approximate date is good.
