### ISSUE TITLE
If Motion to Impound addresses is requested, shouldn't this also appearr on Page 1, section J?

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#518]
I think the interaction between Page 1, Section J 4a, 4b and 4c is not  coded into current MVP version maybe the way it should be. 

@kateleebarry  should 2 be MVP?

**1.** If Page 1, Section J, 4a, 4b or 4c  are requested this does not mean plaintiff is also requesting impoundment, correct?
**2.** **But** if plaintiff requests impoundment of addresses, then Page 1, Section J, 4a, 4b **and** 4c should all be checked, or a refined version is if plaintiff requests that addresses be impounded and plaintiff has indicated that they work outside the home or attend school, the corresponding boxes in section J should be checked. 
**3.** Also we should adjust text in Motion to impound questions to recognize that keeping addresses off the order is not the same thing as impounding. (I don't think this piece is MVP) 

Check language on Page id: plaintiff confidential intro
alf, alf’s lawyer, and the public are not allowed to see this information about you. - needs to be edited to reflect if keep address off order this shows up, otherwise if you did not ask teh court to keep your addresses off the order, they will show up on the order?  Really we need to change the explanation of the Plaintiff Confidential Information form

**Comment by kateleebarry** [comment]
I agree with point 2.  For points 1 and 3, I’ve had judges take the position that keeping the addresses off the order is the same as an impoundment and you need to do the motion. But the problem is that I don’t think courts are consistent and no one really knows what the difference is between impoundment and keeping it off the order. But, at the same time, I don’t think failing to do the motion will actually cause someone’s address to be included. More likely the judge will just say, hey do this motion (which is exactly what happened to me).
