### ISSUE TITLE
Page 1 J(5) Losses suffered by the Plaintiff and J(8) other relief

### ISSUE THREAD

**Issue by CaroRob** [SuffolkLITLab/docassemble-MAVirtualCourt#535]
on page 1 is completely empty, all text is now on addendum, We need the first 100 characters in losses_caused_by_defendant to show up on PDF, with language indicating there is an addendum and the rest go to the addendum, right now it looks as if all text goes into addendum and nothing goes into PDF field.

[1.2.0613 Aubrie Result.pdf](https://drive.google.com/open?id=1SEL5wm8InLbC1meg9Tru5fD1eIZ5Bo7N&authuser=crobinson%40mlri.org&usp=drive_fs)

**Comment by CaroRob** [comment]
Branch  text-fields-on-page-1  trying to address this managed to get losses_caused_by_defendant working but cannot get other_relief to fill @purplesky2016 can you try this?

**Comment by plocket** [comment]
I believe this is because of `skip undefined: True` in the attachment blocks. I think it means that `losses_caused_by_defendant_safe_for_pdf` will not be looked for and will not be defined.

I think `skip undefined: True` changes the model we need to use for defining values of attachment fields. We will need to set losses_caused_by_defendant_safe_for_pdf outside of the attachment block.

I'll try to mock that up.

**Comment by CaroRob** [comment]
Never mind overflow to addendum - @kateleebarry said 7/14/2020 it's ok just to have character limits for these 2 fields  - forgot to change yesterday.  The problem with other relief is that the text isn't accepting return characters - I think
