### ISSUE TITLE
209A: Pattern-based abuse

### ISSUE THREAD

**Issue by kateleebarry** [SuffolkLITLab/docassemble-MAVirtualCourt#574]
For abuse that's very high frequency and not really necessarily discrete, specific incidents, there are a few issues.  For example, I've had a lot of clients where their description of the abuse is basically "he hit me every day," and no one incident really stands out above the rest.  Also, child sexual abuse where it happened many times over a range of years.  

1)  First, on Page 1, Part I, it would be nice if the date could be a range (for example, 2012 through 2016) rather than just the date of the most recent incident.  

![image](https://user-images.githubusercontent.com/63356951/90270931-052bbf80-de29-11ea-9891-87cc03135801.png)

2) Also, we've discussed this a good bit already, but I think the bigger issue probably requires some edits to the affidavit to allow for conduct like this.

**Comment by CaroRob** [comment]
Elizabeth Schonvainer's suggested language was "Has there been a pattern of behavior that has made you afraid?"
I think that is what it was - I would edit it so that it actually makes defendant accountable - haven't thought through completely, and maybe we could have some more explanation.... Does other_parties.familiar() regularly behave in ways that make you afraid? Still need to work on this regular pattern of abuse language.. and thinking of ways to integrate into incidents of abuse... still need to think through but I think this is would a valuable improvement to the way we help people write their affidavit.
